---
name: Jinja2 Linting Action
description: Action to run Jinja2 Linting.
author: L3D <l3d@c3woc.de>

inputs:
  target:
    description: |
      Target for j2lint
      For example 'templates/', './' or 'path/to/jinja2-templates/'
    required: true
runs:
  using: docker
  image: Dockerfile
  env:
    TARGET: ${{ inputs.target }}
branding:
  icon: 'check-circle'
  color: 'blue'
